---
- name: Ensure root can login into MySQL localhost
  shell: "mysql -e \"CREATE USER IF NOT EXISTS 'root'@'{{ item }}'; SET PASSWORD FOR 'root'@'{{ item }}' = '{{ passwd_mysql_root }}';\" -uroot -p'{{ passwd_mysql_root }}'"
  with_items:
    - ::1
    - 127.0.0.1
    - "{{ ansible_ip }}"

- name: Create the MySQL app_user
  shell: "mysql -e \"CREATE USER IF NOT EXISTS '{{ user_name }}'@'{{ item }}'; SET PASSWORD FOR '{{ user_name }}'@'{{ item }}' = '{{ passwd_mysql_app_user }}'; GRANT ALL PRIVILEGES ON *.* TO '{{ user_name }}'@'{{ item }}';\" -uroot -p'{{ passwd_mysql_root }}'"
  with_items:
    - "%"
    - "{{ ansible_ip }}"

- name: Revoke the SUPER privileges from the MySQL app_user
  shell: "mysql -NBe \"REVOKE SUPER ON *.* FROM '{{ user_name }}'@'{{ item }}'\" -uroot -p'{{ passwd_mysql_root }}'"
  with_items:
    - "%"
    - "{{ ansible_ip }}"

#- name: Create the database for website
#  shell: "mysql -e \"CREATE DATABASE '{{ dbname }}';\" -uroot -p'{{ passwd_mysql_root }}'"
#  with_items:
#    - "%"
#    - "{{ ansible_ip }}"

#- name: Create the database for website
#  mysql_db: name={{ dbname }} state=present

  
- name: Copy root .my.cnf file
  template:
    src: ../../templates/root-my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
- name: Create the database for website
  mysql_db: name={{ dbname }} state=present



- name: Restart the MySQL service
  shell: service mysql restart
  become: yes
