---
- hosts: host 
  become: yes
  gather_facts: no
  tasks:
  - name: Apache latest version installation
    yum:
      name: httpd
      state: latest
  - name: Enable service to start on boot up
    service:
      name: httpd
      state: started
  - name: Copy Index test page
    template: 
        src: index.html.j2
        dest: /var/www/html/index.html
    register: Inderx_change

           
  - name: Create firewall rule for apache service
    firewalld:
         port: 80/tcp
         permanent: yes
         immediate: yes
         state: enabled
  - name: Create firewall rule for apache service
    firewalld:
         service: http
         zone: public
         permanent: yes
         immediate: yes
         state: enabled

  - name: Wait for port
    wait_for: port=80

  handlers:
 
  - name: Restart apache service
    service:
      name: httpd
      state: restarted
